### ISSUE TITLE
Calling the wrong until-method?

### ISSUE THREAD

**Issue by enkelmedia** [skybrud/Skybrud.Essentials#16]
Method name does not reflect the method called?

Just wanted to let you know :) 

https://github.com/skybrud/Skybrud.Essentials/blob/7859ff37e5f3e9f42a8ad3c140048cdfafcb287a/src/Skybrud.Essentials/Time/EssentialsDateTime.cs#L141

**Comment by abjerner** [comment]
@enkelmedia yes, this is absolutely wrong 🤦‍♂️ 

Thanks for reporting 👍 

Anyways, the `EssentialsDateTime` class is actually obsolete. But I can see that I made the same mistake in the `EssentialsTime` class. I will look into fixing both 😉

**Comment by enkelmedia** [comment]
=D

I was just browsing the code as some "good night reading" yesterday and posted the issue from the phone so that I didn't forget to do it today.

=D 

All the best!

**Comment by abjerner** [comment]
This has now been fixed 😄 

43a5b6a5a7729efa56eaebdd4e79543de6f42408 adds unit tests that prove the implementation is wrong
d6b11ea25dd961d1c694bf9bfda5c79ee25e9f4b ensures the correct utility method is called

Thanks for the help 👍
