### ISSUE TITLE
Trying to use in .NET Core

### ISSUE THREAD

**Issue by xaiyeon** [skybrud/Skybrud.Essentials#4]
Hi, I'm trying to use this in .NET Core but I get the following error:

Package Skybrud.Essentials 1.0.9 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Skybrud.Essentials 1.0.9 supports: net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.

I wanted to use the pre-release package of Skybrud.Social.Core but I needed the above dependency. Will it be compatible in the future? Sorry for the bother.

**Comment by abjerner** [comment]
@xaiyeon Neither _Skybrud.Social.Core_ or _Skybrud.Essentials_ support .NET Core at the moment. I'd like to add support for .NET Core at some point, but I can't say anything about if and when this will be.

We don't use .NET Core ourselves, so maintaining our packages for the regular .NET framework takes priority. I hope that makes sense ;)

**Comment by abjerner** [comment]
@xaiyeon I've now pushed a new release that also targets **.NET Standard 1.3**. As .NET Core implements .NET Standard, this also means that .NET Core is now supported.

This is however just for *Skybrud.Essentials*. I have yet to update *Skybrud.Social.Core* - this still requires a lot of work.
